### ISSUE TITLE
Feature request: Toggle table

### ISSUE THREAD

**Issue by samrjack** [hat0uma/csvview.nvim#5]
I'd love a command to be added that toggles csvview on and off. Or at least a boolean function that reports if the csvview is enabled. 

Use case is that I have keybindings for csvview but right now it requires 2 keys since I can't programmatically tell if the plugin is enabled or not.

**Comment by hat0uma** [comment]
Thank you for your suggestion!

I've found it useful and added a new command, `CsvViewToggle`, to toggle the CSV view on and off. Please give it a try!

If everything works well, feel free to close the issue.

**Comment by samrjack** [comment]
Awesome! Works great! Thanks for the feature (and the awesome plugin in general) :).
